extern void F77_NAME(dgexpvi)(const int *n,
			      const int *m,
			      const double *t,
			      const int *lt,
			      const double *v,
			      double *w,
			      const double *tol,
			      const double *anorm,
			      const int *ia,
			      const int *ja,
			      const double *a,
			      const int *nz,
			      double *wsp,
			      const int *lwsp,
			      int *iwsp,
			      const int *liwsp,
			      int *itrace,
			      int *iflag);
